//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1990s_Shoes_Selling_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Detail
    {
        public int CartID { get; set; }
        public string ShoesID { get; set; }
        public string StyleType { get; set; }
        public int ColourID { get; set; }
        public int Size { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> BuyingSelection_Status { get; set; }
    
        public virtual Shopping_Cart Shopping_Cart { get; set; }
        public virtual Sho Sho { get; set; }
    }
}
