//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1990s_Shoes_Selling_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string Content { get; set; }
        public Nullable<int> StarRating { get; set; }
        public Nullable<int> ShoesDetailsID { get; set; }
        public string UserID { get; set; }
    
        public virtual Shoes_Details Shoes_Details { get; set; }
        public virtual User User { get; set; }
    }
}
