//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1990s_Shoes_Selling_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Products_At_Shop
    {
        public string ShopID { get; set; }
        public string ShoesID { get; set; }
        public string Size { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Sho Sho { get; set; }
        public virtual Shop_Branchs Shop_Branchs { get; set; }
    }
}
