//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1990s_Shoes_Selling_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSystem
    {
        public int OrderSystemID { get; set; }
        public int OrderID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Status { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Related_staff Related_staff { get; set; }
    }
}
