//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1990s_Shoes_Selling_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderSystems = new HashSet<OrderSystem>();
        }
    
        public int OrderID { get; set; }
        public string UserID { get; set; }
        public int CartID { get; set; }
        public string PaymentInfo { get; set; }
        public Nullable<decimal> EstimatedDeliveryHandlingFee { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string PaymentStatus { get; set; }
        public string RecipientAddress { get; set; }
        public string RecipientName { get; set; }
        public string RecipientPhoneNumber { get; set; }
    
        public virtual Shopping_Cart Shopping_Cart { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSystem> OrderSystems { get; set; }
    }
}
