//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1990s_Shoes_Selling_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoes_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shoes_Details()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int ShoesDetailsID { get; set; }
        public string ShoesID { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> TypeShoesID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Sho Sho { get; set; }
        public virtual Type_Shoes Type_Shoes { get; set; }
    }
}
