//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1990s_Shoes_Selling_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_ShipmentDetails
    {
        public string UserID { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string SpecificAddress { get; set; }
        public string AdministrativeBoundaries { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual User User { get; set; }
    }
}
